const initialMedicalFormState = {
    fullName: '',
    birthDate: '',
    gender: '',
    firstSeizureDate: '',
    isFirstSeizure: false,
    cinNumber: '',
    governorate_id: '',
    city_id: '',
    address: '',
    phoneNumber: '',
    seizureFrequency: '',
    lastSeizureDate: '',
    seizureOccurrence: '',
    seizureDuration: '',
    hasAura: false,
    auraDescription: '',
    seizureTypes: {
        tonicClonic: false,
        absence: false,
        focal: false,
        myoclonic: false,
        atonic: false
    },
    lossOfConsciousness: false,
    bodyStiffening: false,
    jerkingMovements: false,
    eyeDeviation: false,
    incontinence: false,
    tongueBiting: false,
    tongueBitingLocation: '',
    confusion: false,
    headache: false,
    fatigue: false,
    weaknessOneSide: false,
    speechDifficulty: false,
    recoveryDuration: '',
    triggers: {
        sleepDeprivation: false,
        stress: false,
        flashingLights: false,
        fever: false,
        missedMedications: false,
        alcoholDrugUse: false
    },
    usualSeizureTime: '',
    relatedToMenstrualCycle: false,
    medicalHistory: {
        brainInjury: false,
        stroke: false,
        tumor: false,
        meningitisEncephalitis: false,
        intellectualDisability: false
    },
    familyEpilepsyHistory: false,
    onMedication: false,
    medicationNames: '',
    dosage: '',
    duration: '',
    sideEffects: '',
    compliantWithTreatment: false,
    previousEEG: false,
    eegResult: '',
    previousMRI: false,
    mriResult: '',
    bloodTestsDone: false,
    canAttendSchoolWork: false,
    injuryDueToSeizures: false,
    psychosocialIssues: false,
    recentHospitalizations: false,
    otherInformation: '',
    mriPhoto: null,
    seizureVideo: null
};

export default initialMedicalFormState;